# Generated by Django 5.0.4 on 2024-05-01 12:38

import django.core.validators
import django.db.models.deletion
import mande.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("utility", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="sluge"),
                ),
                (
                    "start_date",
                    models.DateField(auto_now=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(
                        default=mande.models.six_month_after_now,
                        verbose_name="End Date",
                    ),
                ),
                ("idp", models.BooleanField(default=False, verbose_name="IDP")),
                (
                    "idp_returnee",
                    models.BooleanField(default=False, verbose_name="IDP/Returnee"),
                ),
                ("refugee", models.BooleanField(default=False, verbose_name="Refugee")),
                ("host", models.BooleanField(default=False, verbose_name="Host")),
                ("male", models.BooleanField(default=False, verbose_name="Male")),
                ("female", models.BooleanField(default=False, verbose_name="Female")),
                (
                    "childern",
                    models.BooleanField(default=False, verbose_name="Childern"),
                ),
                (
                    "childern_age",
                    models.CharField(max_length=10, verbose_name="Childer Name"),
                ),
                ("plw", models.BooleanField(default=False, verbose_name="PLW")),
                ("pwd", models.BooleanField(default=False, verbose_name="PWd")),
                (
                    "Major_Activity",
                    models.TextField(
                        max_length=1000, verbose_name="Major Activity / Delivery"
                    ),
                ),
                ("remarks", models.TextField(blank=True, max_length=300, null=True)),
                ("doc", models.DateField(auto_now_add=True)),
                ("dou", models.DateField(auto_now=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utility.donormodel",
                        verbose_name="Donor",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="utility.locationmodel",
                        verbose_name="Location",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="utility.sectormodel",
                        verbose_name="Sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-doc"],
            },
        ),
        migrations.CreateModel(
            name="MonitorProjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                (
                    "overall_Status",
                    models.CharField(
                        choices=[
                            ("N", "Not Started"),
                            ("S", "On Start"),
                            ("P", "In Progress"),
                            ("C", "Completed"),
                            ("PN", "Pendding"),
                            ("CN", "Canncelled"),
                        ],
                        max_length=50,
                        verbose_name="Overall Status",
                    ),
                ),
                (
                    "pregress_percentage",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Progress Percentage(%)",
                    ),
                ),
                (
                    "progress_status",
                    models.CharField(
                        choices=[
                            ("P", "Within The Plane"),
                            ("PD", "Pendding"),
                            ("NS", "Lag Behind Plane"),
                            ("E", "Execute Plane"),
                        ],
                        max_length=200,
                    ),
                ),
                ("doc", models.DateField(auto_now_add=True)),
                ("dou", models.DateField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mande.projectmodel",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Monitor",
                "verbose_name_plural": "Project Monitors",
                "ordering": ["-doc"],
            },
        ),
    ]
