# Generated by Django 5.0.4 on 2024-05-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mande", "0002_alter_projectmodel_childern_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitorprojectmodel",
            name="overall_Status",
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="overall_Status",
            field=models.CharField(
                choices=[
                    ("N", "Not Started"),
                    ("S", "On Start"),
                    ("P", "In Progress"),
                    ("C", "Completed"),
                    ("PN", "Pendding"),
                    ("CN", "Canncelled"),
                ],
                default=[
                    ("N", "Not Started"),
                    ("S", "On Start"),
                    ("P", "In Progress"),
                    ("C", "Completed"),
                    ("PN", "Pendding"),
                    ("CN", "Canncelled"),
                ],
                max_length=50,
                verbose_name="Overall Status",
            ),
        ),
    ]
